# Generated by Django 6.1.1 on 2026-09-12 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwordprogress',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
