# Generated by Django 6.1.1 on 2026-09-12 10:17

from django.db import migrations

WORDS = [
    ('hello', 'привет', '[həˈloʊ]', 'other', 'Hello, how are you?'),
    ('goodbye', 'пока', '[ˌɡʊdˈbaɪ]', 'other', 'Goodbye, see you tomorrow!'),
    ('please', 'пожалуйста', '[pliːz]', 'other', 'Please, close the door.'),
    ('thanks', 'спасибо', '[θæŋks]', 'other', 'Thanks for your help.'),
    ('water', 'вода', '[ˈwɔːtər]', 'noun', 'Can I have some water?'),
    ('food', 'еда', '[fuːd]', 'noun', 'The food here is delicious.'),
    ('house', 'дом', '[haʊs]', 'noun', 'We live in a small house.'),
    ('friend', 'друг', '[frend]', 'noun', 'She is my best friend.'),
    ('book', 'книга', '[bʊk]', 'noun', 'I am reading a new book.'),
    ('time', 'время', '[taɪm]', 'noun', 'What time is it?'),
    ('good', 'хороший', '[ɡʊd]', 'adjective', 'This is a good idea.'),
    ('big', 'большой', '[bɪɡ]', 'adjective', 'They bought a big car.'),
    ('happy', 'счастливый', '[ˈhæpi]', 'adjective', 'She looks happy today.'),
    ('to go', 'идти / ехать', '[ɡoʊ]', 'verb', 'I go to school every day.'),
    ('to eat', 'есть (кушать)', '[iːt]', 'verb', 'We eat dinner at 7 pm.'),
    ('to speak', 'говорить', '[spiːk]', 'verb', 'Do you speak English?'),
    ('quickly', 'быстро', '[ˈkwɪkli]', 'adverb', 'He ran quickly to the bus.'),
    ('today', 'сегодня', '[təˈdeɪ]', 'adverb', 'Today is a beautiful day.'),
]


def seed_words(apps, schema_editor):
    Language = apps.get_model('core', 'Language')
    Deck = apps.get_model('vocabulary', 'Deck')
    Word = apps.get_model('vocabulary', 'Word')

    english = Language.objects.get(code='en')
    deck, _ = Deck.objects.get_or_create(
        language=english,
        owner=None,
        name='Основы',
        defaults={'description': 'Базовые слова для начинающих.'},
    )

    for text, translation, transcription, part_of_speech, example in WORDS:
        word, _ = Word.objects.get_or_create(
            language=english,
            owner=None,
            text=text,
            defaults={
                'translation': translation,
                'transcription': transcription,
                'part_of_speech': part_of_speech,
                'example_sentence': example,
            },
        )
        word.decks.add(deck)


def remove_words(apps, schema_editor):
    Deck = apps.get_model('vocabulary', 'Deck')
    Word = apps.get_model('vocabulary', 'Word')
    Word.objects.filter(language__code='en', owner__isnull=True, text__in=[w[0] for w in WORDS]).delete()
    Deck.objects.filter(owner__isnull=True, name='Основы').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0002_userwordprogress_is_favorite'),
        ('core', '0002_seed_english_language'),
    ]

    operations = [
        migrations.RunPython(seed_words, remove_words),
    ]
