# Generated by Django 6.1.1 on 2026-09-14 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0004_seed_basic_german_words'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='level',
            field=models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], default='A1', max_length=2),
        ),
    ]
