# Generated by Django 6.1.1 on 2026-09-12 08:26

from django.db import migrations


def seed_english(apps, schema_editor):
    Language = apps.get_model('core', 'Language')
    Language.objects.get_or_create(code='en', defaults={'name': 'English'})


def remove_english(apps, schema_editor):
    Language = apps.get_model('core', 'Language')
    Language.objects.filter(code='en').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_english, remove_english),
    ]
